# Generated by Django 3.2 on 2021-07-21 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(default=0)),
                ('shipping_address', models.CharField(max_length=255)),
                ('order_address', models.CharField(max_length=255)),
                ('order_email', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('PP', 'Pending Payment'), ('PR', 'Processing'), ('OH', 'On Hold'), ('CD', 'Completed'), ('CA', 'Cancelled')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('weigth', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('weigth', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('shipment_status', models.CharField(choices=[('PR', 'Processing'), ('OH', 'Sending'), ('CD', 'Received')], default='PR', max_length=2)),
                ('shipping_address', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(default=0)),
                ('shipping_address', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PR', 'Processing'), ('PD', 'Paid'), ('RJ', 'Rejected')], default='PR', max_length=2)),
                ('orders', models.ManyToManyField(to='commerce.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(to='commerce.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='commerce.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
