# Generated by Django 3.2 on 2021-07-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, to='commerce.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='commerce.Order'),
        ),
    ]
